# BEGIN_KITTY_THEME
# Adwaita darker
include current-theme.conf
# END_KITTY_THEME

tab_bar_style powerline
tab_bar_edge top
window_padding_width 6
enable_audio_bell no
font_family FiraMono Nerd Font
font_size 12
background_opacity 0.8
enable_layouts tall:bias=50;full_size=1;mirrored=false
symbol_map       U+1F300-U+1FAFF Noto Color Emoji

# cursor_trail 10
# cursor_trail_start_threshold 0
# cursor_trail_decay 0.01 0.7
# cursor_shape block
# cursor_blink true
