# BEGIN_KITTY_THEME
# Liquid Carbon Transparent
include current-theme.conf
# END_KITTY_THEME

tab_bar_style powerline 
tab_bar_edge top
window_padding_width 10
enable_audio_bell no
font_family 0xProto Nerd Font 
font_size 13.5
background_opacity 0.8
enable_layouts tall:bias=50;full_size=1;mirrored=false
