# BEGIN_KITTY_THEME
# Adwaita darker
include current-theme.conf
# END_KITTY_THEME

tab_bar_style powerline 
tab_bar_edge top
window_padding_width 10
enable_audio_bell no
font_family Hack Nerd Font 
font_size 12
background_opacity 0.7
enable_layouts tall:bias=50;full_size=1;mirrored=false
