" Map escape to jj

" Syntax highlighting
syntax on

" Set FZF Default to Ripgrep (must install ripgrep)
let $FZF_DEFAULT_COMMAND = 'rg --files --hidden --follow --no-ignore-vcs'

" Options viewable by using :options
" Set options viewable by using :set all
" Or help for individual configs can be accessed :help <name>
set nocompatible
set redrawtime=10000
set background=dark
set laststatus=2
set noerrorbells
set tabstop=2 softtabstop=2
set shiftwidth=2
set expandtab
set smartindent
set nu
set nowrap
set nobackup
set undodir=~/.vim/undordir
set undofile 
set incsearch
set relativenumber
set cursorline
set cursorcolumn
set termguicolors

" Column set to column 100
set colorcolumn=100

" Column color set to grey
highlight ColorColumn ctermbg=1

" Plugins
call plug#begin('~/.vim/plugged')

" Formatter
Plug 'prettier/vim-prettier', { 'do': 'yarn install' }

" A light and configurable statusline/tabline plugin for Vim
Plug 'itchyny/lightline.vim'

" Directory tree
Plug 'preservim/nerdtree'

" Syntax highlighting for languages
Plug 'sheerun/vim-polyglot'

" Gruvbox color theme
Plug 'morhetz/gruvbox'

" Vim Dracula Color Theme
Plug 'dracula/vim',{'as':'dracula'}

" Vim Tokyo Night Color Theme
Plug 'ghifarit53/tokyonight-vim'

" Vim Everforest Color Theme
Plug 'sainnhe/everforest'

" Vim Moonfly Color Theme
Plug 'bluz71/vim-moonfly-colors',{'as':'moonfly'}

" Vim Sunbather Color Theme 
Plug 'nikolvs/vim-sunbather'

" Vim SpaceCamp Color Theme 
Plug 'jaredgorski/spacecamp'

" Autocomplete Plugin
Plug 'vim-scripts/AutoComplPop'

" Auto Pair Plugin
Plug 'bundle/auto-pairs'

" vCoolor Plugin - Edit Hex Color Thru Vim
Plug 'ap/vim-css-color'

call plug#end()

" Start nerdtree whit vim 
" autocmd VimEnter * NERDTree

" Set the prettier CLI executable path
let g:prettier#exec_cmd_path = "~/.vim/plugged/vim-prettier/node_modules/prettier"
" Max line length that prettier will wrap on: a number or 'auto'
let g:prettier#config#print_width = 100 " default is 'auto'

" Tokyonight theme config
" let g:tokyonight_style = 'night'
" let g:tokyonight_enable_italic = 1 


" set background=dark
colorscheme spacecamp
