general {
    idle_timeout = 300            # Tempo em segundos antes de considerar o sistema inativo (5 minutos)
    poll_rate = 60                # Frequência de verificação de inatividade em segundos
    idle_callback = hyprlock      # Comando para bloquear a tela
    resume_callback = echo "Resumed from idle"  # Comando opcional ao retomar da inatividade
}

event = idle, 600, loginctl suspend  # Suspende o sistema após 10 minutos de inatividade

